FROM ipython/scipyserver

RUN mkdir /pandas-cookbook
WORKDIR /pandas-cookbook
RUN mkdir ./cookbook ./cookbook_polars ./data ./images

COPY cookbook/*.ipynb ./cookbook/
COPY cookbook_polars/*.ipynb ./cookbook_polars/
COPY cookbook_polars/*.py ./cookbook_polars/
COPY images/*.png ./images/
COPY data/* ./data/

WORKDIR /pandas-cookbook/cookbook_polars/
